controller_manager:
  ros__parameters:
    update_rate: 10
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    hiwonder_xarm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    pan_tilt_controller:
      type: forward_command_controller/ForwardCommandController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_front_wheel_joint','left_rear_wheel_joint']
    right_wheel_names: ['right_front_wheel_joint','right_rear_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.072

    # use_stamped_vel: false

    # open_loop: false    

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters:
hiwonder_xarm_controller:
  ros__parameters:
    joints:
      - xarm_1_joint
      # - xarm_1_joint_mirror
      - xarm_2_joint
      - xarm_3_joint
      - xarm_4_joint
      - xarm_5_joint
      - xarm_6_joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity



    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    # allow_partial_joints_goal: true
    # constraints:
    #   goal_time: 0.0

    # interpolation_method: linear

    
    
    # Trajectory constraints
    # set rate monitoring period to 10ms
    
    # state_publish_rate: 10.0  # Hz
    # action_monitor_rate: 5.0  # Hz


    # constraints:
    #   stopped_velocity_tolerance: 0.01
    #   goal_time: 0.0
    
    # # Allow partial goals
    # allow_partial_joints_goal: false
    
    # # Allow integrating velocity commands
    # allow_integration_in_place: false
    
    # # Trajectory execution parameters
    # allow_nonzero_velocity_at_trajectory_end: true

pan_tilt_controller:
  ros__parameters:
    joints: ["pan_joint", "tilt_joint"]
    interface_name: position


